### ISSUE TITLE
SearchEngine.Clone() fails with null cache

### ISSUE THREAD

**Issue by kentskinner** [ZviRosenfeld/MinMaxSearch#9]
SearchEngine engine = new SearchEngine();
SearchEngine engine2 = engine.Clone();

Fails with:
 MinMaxSearch.Exceptions.MinMaxSearchException
 Can't set cacheMode to NoCache when using a cache. If you don't want to use a cache, please use the empty constructor.

**Comment by ZviRosenfeld** [comment]
Hi Kent,

Thank you for reporting this bug. I've fixed it and uploaded the new NuGet version to nuget.org (version 1.5.5). Updating to that version should fix the issue.

Thanks,
Zvi
